# MultiDATA API
swagger: '2.0'
info:
  title: MultiDATA API
  description: Servicios de integracion MultiDATA Chile
  version: "1.0.0"
# the domain of the service
host: api.multidatachile.cl
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /services
produces:
  - application/xml
paths:
  '/checkcard/{rut}/{serial}':
    get:
      summary: Valida el estado y validez de un carnet de identidad chileno.
      description: |
        El formato del rut debe ser el (11111111-1) sin incluir puntos y letras deben ser mayúscula. El formato del número de serie o número de documento puede variar.
      parameters:
        - name: rut
          in: path
          description: Rut a validar
          required: true
          type: string
        - name: serial
          in: path
          description: Serial a validar
          required: true
          type: string
      tags:
        - checkcard
      responses:
        200:
          description: An xml containing results
          schema:
            type: array
            items:
              $ref: '#/definitions/Carnet'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Carnet:
    type: object
    properties:
      vigente:
        type: string
        description: Validación del documento (OK o ER)
  Error:
    type: object
    properties:
      Sts:
        type: integer
        format: int32
      Src:
        type: string
